Add connections rpc endpoints
mathesar-foundation/mathesar pull request #3348
Opened 2023-12-12 07:25 UTC by mathemancer

Fixes #3293 

This adds 3 endpoints at:

-  `POST api/ui/v0/connections/create_from_known_connection`
-  `POST api/ui/v0/connections/create_from_scratch`
-  `POST api/ui/v0/connections/create_with_new_user`

to allow the creation of connections via the API.

As a bonus, it also adds a function

`msar.create_basic_mathesar_user(username text, password_ text) RETURNS TEXT` to the SQL installation script that can let a DBA easily add a Mathesar user with the proper permissions from the database layer.

**Technical details**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-12-14 06:35 UTC, mathemancer commented
@Anish9901 This is ready for review, but needs manual testing. Our current testing suite is designed around reusing the database server where the running service has its Django tables, and most of the actions enabled by these endpoints would modify that database without making cleanup guaranteed (for example, if tests are cancelled). Thus, I'm electing to avoid writing API tests (or any tests that use the backing functions) until we have overhauled how the testing suite works.

I'll update the description to make manual testing easier.

2023-12-15 16:40 UTC, seancolsen approved these changes
I haven't tested this exhaustively, but in its most basic form, this is working for me. As far as I'm concerned, we can sort out any remaining deficiencies in subsequent PRs.

2023-12-19 21:14 UTC, Anish9901 requested changes
@mathemancer I've a found a few issues,
- Will we be supporting adding databases through the env variable `MATHESAR_DATABASES`? I don't think so. However, if we _are_, this PR removes the error handling for unique violations that occur during server restarts.
- The 1st JSON provided in the PR description for `create_from_scratch` contains the key `create_database: true` which according to the wiki [spec](https://wiki.mathesar.org/design/specs/new-db-connection-form/#case-b-manually-entering-new-connection-credentials) and the implentation in the PR doesn't match up. However the spec and the implementation do contain `sample_data` which requires a database to be present. The JSON fails resulting in a 500 in case the database doesn't exist.
- I tried 2nd JSON for `create_from_scratch` without a database, which resulted in the connection getting created, I then created the database using psql, after which patched the connection with the same JSON but there was no attempt to install mathesar on the database.  
- Executing any of the JSONs twice results in a unique violation with a 500 instead of 400.(due to `db_model.save()` in `_save_and_install`)

2023-12-20 05:23 UTC, mathemancer commented on mathesar/install.py
> +        port=db_model.port,
I don't understand this one. This is using the 'nickname' of databases from the saved DB models.

2023-12-20 05:58 UTC, Anish9901 commented on mathesar/install.py
> +        port=db_model.port,
That's true but notice the last couple of lines of the main func, `install_on_db_with_key` is only called in main and for the dbs present in the `settings.DATABASES` dict.

2023-12-20 16:19 UTC, Anish9901 approved these changes

2023-12-20 16:30 UTC, merged

2023-12-20 17:49 UTC, kgodey commented
@Anish9901 @mathemancer Is there a ticket to track the follow up work we discussed at today's meeting, or has that all already been handled?

2023-12-20 17:56 UTC, seancolsen commented
@mathemancer you said:

> @seancolsen what do you think about that bit?

Hmmm, it's a little hard for me to tell since I haven't been following this thread between you and Anish so I don't really have enough context to understand the problem. If you'd still like my input would you be able to summarize this into a specific question for me?

2023-12-21 06:01 UTC, mathemancer commented
@seancolsen As we discussed and agreed previously, I don't think we should delete or get rid of connections if we fail to connect to the database the connection references. This is because there are a number of reasons that could happen, many of which are _not_ that the DB is deleted. For now, that means throwing an internal server error (500) if we try to reach a database and fail, since that's most reasonable for "couldn't connect between the service and a database". We should get more granular later.

The new question is: What if we can't reach the database when _creating_ a connection? There are multiple scenarios:

- We can reach the server, but can't connect to the DB
  - It doesn't exist
  - It exists, but the user in the connection doesn't have the `CONNECT` privilege on it
- We can't reach the server at all
  - We're copying a connection from a previous connection
    - The previous connection has connected successfully at least once
    - The previous connection has never actually connected

What error(s) should we throw, and what should a user's next steps be?

At the moment, everything is wrapped up in a 500, along with an error message with some more detail about what specifically happened. We still create the connection, for the same reasons we don't delete or remove a connection that isn't working (this is a debatable choice, but makes at least some sense). This is a simplifying choice, but also may compress the situation too much for the user to know how to proceed.

2023-12-21 14:48 UTC, mathemancer commented
> @Anish9901 @mathemancer Is there a ticket to track the follow up work we discussed at today's meeting, or has that all already been handled?

I think we need to work out the requirements. I've started an issue here: #3369

2023-12-22 17:10 UTC, seancolsen commented
@mathemancer thanks for the summary. These are good questions. I can see advantages and disadvantages to various approaches. I think I would need to talk this through more in order to form opinions on it. The issue #3369 that you opened seems like a good placeholder for that sort of discussion.