Improve exception handling while failing to connect to a database
mathesar-foundation/mathesar pull request #3388
Opened 2024-01-04 20:54 UTC by Anish9901

Fixes #3329 
Fixes #3361 (part 2)

**Technical details**

This PR globally catches any `OperationalError` that occurs throughout the app. This error is generally caused when an attempt to connect to a database fails, due to reasons such as invalid credentials, db deleted outside mathesar, etc.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-01-12 02:49 UTC, mathemancer requested changes
Won't the rearrangement of the install functions (i.e., by moving the save step after the installation step) leave the possibility of inconsistencies? I.e., if we can't save the model, there could be a problem where the user ends up with Mathesar tooling installed on their user DB, but no working connection to that DB. I'd rather have it the other way around. I.e., we should save, then install, then roll back the save if the installation fails.

2024-01-16 07:22 UTC, mathemancer commented
> we do require an internal database connection at the start for our Django server to make migrations on the target database if the django_db_url is not configured properly the app won't even start. The only way I can think of this happening is when django server is successfully started, then the pg server on which the internal db is hosted is shut down/ not accepting connections and then there is an attempt to add a connection via the UI. I am curious to know what other scenarios you envision when model instances might fail to save?

Hmmm That's a really good point that the user will definitely at least have some working connection, or the `install` step would already fail. I was thinking about uniqueness violations resulting in the model instance failing to save. The `nickname` should be unique I think.

2024-01-16 08:21 UTC, mathemancer requested changes
See my specific comment. The `db` library needs to stand alone, and shouldn't know about Django model instances.

2024-01-16 13:14 UTC, Anish9901 commented on db/install.py
> +        db_model,
That makes sense. I've reverted the function signature.

2024-01-16 14:48 UTC, mathemancer approved these changes
Okay, I think we're in business here. Nice work, @Anish9901 .

2024-01-16 14:59 UTC, merged