Backend support for configurable record summaries
mathesar-foundation/mathesar pull request #3978
Opened 2024-10-21 21:26 UTC by seancolsen

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-10-21 21:31 UTC, seancolsen commented
This state due to some rough edges and unresolved architectural questions, but I've got some progress...

![image](https://github.com/user-attachments/assets/f4d069d9-3015-4195-8f8a-db5806cc523b)

In this `records.list` request, I'm passing in _all_ the record summary templates to the DB layer. This was one possible implementation that we discussed, but not necessarily one that I feel strongly about using. It just happened to be the easiest starting place.

2024-10-25 07:06 UTC, mathemancer requested changes
The only blocking change is to remove the file `hardcopy.0`, unless I'm missing something.

Other than that, I think I'm good with this.

2024-10-25 07:06 UTC, mathemancer commented on hardcopy.0
I think this file should be removed.

2024-10-25 12:18 UTC, seancolsen commented on hardcopy.0
Oh geeze, how embarrassing. 🤣 That's a dump from GNU Screen that probably got there from me fat-fingering a keyboard shortcut. Someday I'll finally switch to tmux 🙄 I've removed the file in 2397661a89ff7cd9bb02e65d4669043baf6b4051

2024-10-25 12:20 UTC, seancolsen commented on db/sql/00_msar.sql
> +      ) FILTER (WHERE summary_cte_%1$s.key IS NOT NULL), '{}'::jsonb
Yeah, I had to do this in order to make the _self_ summary query use the same structure as the _linked_ summary query.

2024-10-25 12:24 UTC, seancolsen commented on db/sql/00_msar.sql
> +    ELSE chr(10) || array_to_string(join_clauses, chr(10))
Yeah, that's fair. I changed these to `E'\n'` in ab8161b814e2f6cb7e95baa01e87b973d483c51c

2024-10-25 12:25 UTC, seancolsen commented
@mathemancer this is ready for re-review now.

2024-10-28 07:15 UTC, mathemancer approved these changes
Okay, LGTM

2024-10-28 07:24 UTC, merged