Add ability to export tables
mathesar-foundation/mathesar pull request #4090
Opened 2024-12-17 20:17 UTC by pavish

Fixes #4067

# DRAFT PR - details to come

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-12-18 13:49 UTC, pavish commented
@ghislaineguerin @kgodey I've assigned you to this PR to get a sign off on the UX.

2024-12-19 03:01 UTC, mathemancer requested changes
The overall method seems reasonable. Nice work on that!

However, I think most of the SQL code and a large part of the Python code could be removed if you can get `ServerCursor.fetchmany` working (or just use the builtin `itersize` param and loop through rows one at a time clientside).

If there's a really good reason that doesn't work, what is it?

Also, please just pull apart the `msar.list_records_from_table` result to get the actual records to return. I don't want to have to maintain that formatted query in multiple places if we can avoid it. Alternatively, you could extract the CTE-generating code and call it from both the record lister and the iterable record lister SQL functions. I prefer the former approach, since it prioritizes the efficiency of the hot path, i.e., listing records for display normally.

2024-12-19 14:40 UTC, pavish commented on db/sql/00_msar.sql
> +    msar.build_where_clause(tab_id, filter_)
> This code replication is avoidable by just calling the record lister, then pulling apart the result.

The record lister queries everything into a single json, so calling that method means that we cannot use a cursor to iterate through the results.

2024-12-19 14:47 UTC, pavish commented on db/connection.py
> +        yield rows
1. I needed a SQL call to build the select query which accepts filters and sorting in the exact format as `list` does.
2. I needed a SQL call to fetch the names of the columns (as the existing functions rely on oids).
3. I needed a server side cursor.

If we use ServerCursor for the results, we'd need to make additional calls for `build_select_query` and `fetch_selectable_column_names`. We'd also need to have additional logic to ensure that the column names are in the same order as the columns in the results.

It's much simpler to fetch everything via a single plpgsql function.

2024-12-20 03:24 UTC, mathemancer commented on db/sql/00_msar.sql
> +    msar.build_where_clause(tab_id, filter_)
Regardless, maintaining that SQL construction in multiple different functions isn't a good idea. We'll need to find a better way.

2025-01-07 19:52 UTC, pavish commented
@mathemancer The PR is ready for review again, with the following discussed changes:
- Return records as setof jsonb (as opposed to jsonb array or setof record)
- Use ServerCursor class to create the underlying cursor

This also moves some common expressions and ctes into a different function.

2025-01-08 09:48 UTC, mathemancer approved these changes
Okay, I left some comments of things I'd improve, but nothing blocking.

I'll leave it to you to merge the specific suggested function (if you want; it's not required), and then merge this PR.

2025-01-08 09:48 UTC, mathemancer commented on db/sql/00_msar.sql
> +CREATE OR REPLACE FUNCTION msar.build_expr_and_ctes_for_enriched_results(
I don't think blobbing all this logic into this function is a good idea.
- It obscures the logic and what the inputs/outputs are from each spot the various returned pieces are used
- It returns a complex object that isn't useful unless you look at the function's source code: It's not possible from the signature to determine what the function actually returns
- It's not documented, exacerbating the above problem.

2025-01-08 12:22 UTC, pavish commented on db/sql/00_msar.sql
> +CREATE OR REPLACE FUNCTION msar.build_expr_and_ctes_for_enriched_results(
I added a commit to improve the name of this function and some comments: https://github.com/mathesar-foundation/mathesar/pull/4090/commits/56481fdd6a6f6a52b8ea93e73f1ad166e38f1e21.

I hope this should alleviate some of the concerns. However, I'm open to refactoring this later if required.

2025-01-08 12:28 UTC, merged