Fixed the misalignment in number text of money type cell
mathesar-foundation/mathesar pull request #4097
Opened 2024-12-23 17:47 UTC by sharath-1517

Fixes #4085

**Technical details**

- I have added a isMoneyCell flag in the `SteppedInputCell.svelte` component to make sure that only money fields will get the font-variant-numeric: tabular-nums;` style.

**Screenshots**

- Before:  
![image](https://github.com/user-attachments/assets/a7324580-dfbe-44d0-8b57-1f816580feb1)

- After (See the decimal values):
<img width="164" alt="image" src="https://github.com/user-attachments/assets/b1a352e8-e7ab-489f-a423-a380609fd9d2" />

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2025-01-06 14:33 UTC, seancolsen requested changes
Sorry @sharath-1517, but this is not going to be a clean approach. We should keep the `SteppedInputCell` component entirely decoupled from the concept of data types. Adding an `isMoneyCell` prop couples it tightly to that data type and introduces mess that would be tricky to disentangle later on.

It's worth mentioning that this cell-level code is already _super_ messy. It really is begging for a refactor, but we're not prioritizing that at the moment.

Notice how money cells and number cells are right aligned instead of left aligned? We should follow the same pattern when setting this new CSS.

1. Set the CSS within `CellWrapper`, and add a new prop to handle it. Name your prop in accordance with what is happening inside the component, not outside. So don't mention "money". I suggest a boolean prop named `useTabularNumbers` which defaults to `false`. Then a class with a similar name.

1. Forward that prop up through `SteppedInputCell`.

1. Set the prop to `true` within the respective components for Number, Money, Date, Date Time, Time, and Duration cell types.

2025-01-06 18:45 UTC, sharath-1517 commented
Hey @seancolsen , I have added the guided changes. Requesting for a review. Thanks!

2025-01-06 22:19 UTC, seancolsen approved these changes
I pushed 4ec84e7892a21ea226c566f50de277a0c5c73245 to properly handle Duration cells.

The code looks good to me now.

2025-01-06 22:23 UTC, seancolsen commented
I'm going to hold off on merging since I'm not actually able to reproduce this issue the way Zack was. For me, all numbers render equally spaced, even before this PR. I suspect that the difference in observations between me and Zack is due to our systems using different fonts. Mathesar uses system fonts, so different users will see the UI with different fonts. That behavior is an intentional design choice. But it makes it somewhat tricky here.

@zackkrida can you give this PR a whirl and see if it fixes the issue as you originally described it? If so, please merge.

2025-01-06 23:10 UTC, zackkrida commented
Excellent, this indeed fixes the issue. Thank you @sharath-1517! 

With the new CSS class disabled:

![image](https://github.com/user-attachments/assets/13f6cbb6-6396-42a9-ae51-a2738c5ece02)

With it enabled:

![Screenshot From 2025-01-06 18-06-44](https://github.com/user-attachments/assets/8a1172ae-d215-41eb-ac12-a3f5a419a727)

In the font in use here, Canterell, the "1"s are a particularly good example of the change.

2025-01-06 23:10 UTC, zackkrida approved these changes

2025-01-06 23:13 UTC, merged

2025-01-07 02:34 UTC, sharath-1517 commented
> Excellent, this indeed fixes the issue. Thank you @sharath-1517! 
> 
> With the new CSS class disabled:
> 
> ![image](https://github.com/user-attachments/assets/13f6cbb6-6396-42a9-ae51-a2738c5ece02)
> 
> With it enabled:
> 
> ![Screenshot From 2025-01-06 18-06-44](https://github.com/user-attachments/assets/8a1172ae-d215-41eb-ac12-a3f5a419a727)
> 
> In the font in use here, Canterell, the "1"s are a particularly good example of the change.

Thank you Zach!

2025-01-07 02:34 UTC, sharath-1517 commented
> I pushed 4ec84e7892a21ea226c566f50de277a0c5c73245 to properly handle Duration cells.
> 
> The code looks good to me now.

Thanks Sean!